# Site settings
baseurl = "http://isadorasophia.com/"
languageCode = "en-us"
title = "Isadora Sophia"
theme = "hugo-cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

enableEmoji = true

[params]
	name = "Isadora Sophia"
	description = "A short description about what I do and who I am."
	bio = "Programmer - Researcher - Dreamer"
	# Enter optionally your twitter account
	twitter = "isadorasophia"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "About"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I like designing new worlds."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Page doesn't exist!"
	subtitle404 = "Sorry :("

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/isadorasophia"
    github   = "https://github.com/isadorasophia"
    linkedin = "https://www.linkedin.com/in/isadora-sophia-488726107"
    email    = "mailto:isadorasophiagr@gmail.com"
